<?php echo $this->headTitle("Thêm Sản Phẩm") ?>
<article class="ui container wrapper">    
    <?php echo $this->partial('partial/nav_shop'); ?>
    <?php echo $this->partial('partial/errors'); ?>
    <?php 
    $form = $this->form;
    $form->prepare();
    $form->setAttribute('action',$this->url('shop/defaults',array('action' => 'shop-add')));
    $form->setAttribute('class','ui form');
    $form->setAttribute('id','form_add');
    echo $this->form()->openTag($form);
    echo $this->formElement($form->get('csrf'));
    ?>
    <input type="hidden" name="password_hidden" value="<?php echo $this->pass_random; ?>">
      <div class="field">
        <label>Tên đăng nhập</label>
        <input type="text" name="username" value="">
      </div>
      <div class="field">
        <label>Mật khẩu</label>
        <div class="ui action disabled input" onclick="copyText('password')">

		  <input type="text" class="" value="<?php echo $this->pass_random ?>" id="password" name="password" >
		  
		</div>

      </div>
      <div class="field">
        <label>Game</label>
        <select class="ui fluid dropdown" name="game">
        	<?php foreach($this->FrontendData()->Category() as $key => $category): ?>
	        <option value="<?php echo $key; ?>"><?php echo $category; ?></option>
	    	<?php endforeach; ?>
	    </select>
      </div>
      <div class="field">
        <label>Mô tả</label>
        <textarea name="description" style="border-radius: 0px;"></textarea>
      </div>
      <div class="ui segment d-table" style="border-radius: 0px;">
      	<button type="button" class="ui button mini mb-15" id="dexuatgia">ĐỀ XUẤT GIÁ</button>
	    <div class="field d-table-row">
	      	<div class="ui toggle checkbox table-cell">
		        <input type="checkbox" name="hours[3]" checked class="hidden">
		        <label>3 giờ</label>
	     	</div>
			<input type="text" name="money[3]" id="hours_3" class="input-rent table-cell">
	    </div>
	    <div class="field d-table-row">
	      	<div class="ui toggle checkbox table-cell">
		        <input type="checkbox" name="hours[8]" checked class="hidden">
		        <label>8 giờ</label>
	     	</div>
			<input type="text" name="money[8]" id="hours_8" class="input-rent table-cell">
	    </div>
	    <div class="field d-table-row">
	      	<div class="ui toggle checkbox table-cell">
		        <input type="checkbox" name="hours[20]" checked class="hidden">
		        <label>20 giờ</label>
	     	</div>
			<input type="text" name="money[20]" id="hours_20" class="input-rent table-cell">
	    </div>
	    <div class="field d-table-row">
	      	<div class="ui toggle checkbox table-cell">
		        <input type="checkbox" name="hours[36]" checked class="hidden">
		        <label>36 giờ</label>
	     	</div>
			<input type="text" name="money[36]" id="hours_36" class="input-rent table-cell">
	    </div>
	    <div class="field d-table-row">
	      	<div class="ui toggle checkbox table-cell">
		        <input type="checkbox" name="hours[72]" checked class="hidden">
		        <label>72 giờ</label>
	     	</div>
			<input type="text" name="money[72]" id="hours_72" class="input-rent table-cell">
	    </div>
	  </div>
      <div class="field">
	    <div class="ui checkbox">
	      <input type="checkbox" name="is_giahan" checked="checked" class="hidden">
	      <label>Cho phép gia hạn</label>
	    </div>
	  </div>
      <button type="submit" class="ui secondary button fluid">
        THÊM SẢN PHẨM
      </button>
    <?php $this->form()->closeTag(); ?>
</article>