<div class="container">
    <div class="row justify-content-center">
        <div class="col-10 col-sm-5 form-login">
            <?php 
                $form = $this->form;
                $form->prepare();
                $form->setAttribute('action',$this->url('zflex/auth',array('action' => 'login')));
                echo $this->form()->openTag($form);
                echo $this->formElement($form->get('csrf'));
            ?>
            <div class="d-flex form-login-header justify-content-between align-items-center">
                <p class="display-4">ZFLEX</p>
                <p><i class="icon-versions"></i> Version 1.0</p>
            </div>
            <div class="form-group">
                <?php 
                    echo $this->formElement($form->get('username'));
                    echo $this->formElementErrors($form->get('username'));
                ?>
            </div>
            <div class="form-group">
                <?php 
                    echo $this->formElement($form->get('password'));
                    echo $this->formElementErrors($form->get('password'));
                ?>
            </div>
            <div class="form-group">
                <button class="btn btn-info btn-block">Login</button>
            </div>
            <?php
                $this->form()->closeTag();
            ?>
            <?php 
                echo $this->Layout()->FlashMessenger();
            ?>
        </div>
    </div>   
</div>