<?php

namespace DoctrineORMModule\Proxy\__CG__\ZFlex\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Shop extends \ZFlex\Entity\Shop implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', 'id', 'shop_name', 'url_facebook', 'phone_number', 'banner', 'bank', 'stk_bank', 'ctk_bank', 'time_created', 'customer', 'comment_shop', 'report_shop', 'report_rent');
        }

        return array('__isInitialized__', 'id', 'shop_name', 'url_facebook', 'phone_number', 'banner', 'bank', 'stk_bank', 'ctk_bank', 'time_created', 'customer', 'comment_shop', 'report_shop', 'report_rent');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Shop $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setId($id)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setId', array($id));

        return parent::setId($id);
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function setShopName($shop_name)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setShopName', array($shop_name));

        return parent::setShopName($shop_name);
    }

    /**
     * {@inheritDoc}
     */
    public function getShopName()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getShopName', array());

        return parent::getShopName();
    }

    /**
     * {@inheritDoc}
     */
    public function setUrlFacebook($url_facebook)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setUrlFacebook', array($url_facebook));

        return parent::setUrlFacebook($url_facebook);
    }

    /**
     * {@inheritDoc}
     */
    public function getUrlFacebook()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getUrlFacebook', array());

        return parent::getUrlFacebook();
    }

    /**
     * {@inheritDoc}
     */
    public function setPhoneNumber($phone_number)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPhoneNumber', array($phone_number));

        return parent::setPhoneNumber($phone_number);
    }

    /**
     * {@inheritDoc}
     */
    public function getPhoneNumber()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPhoneNumber', array());

        return parent::getPhoneNumber();
    }

    /**
     * {@inheritDoc}
     */
    public function setBanner($banner)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBanner', array($banner));

        return parent::setBanner($banner);
    }

    /**
     * {@inheritDoc}
     */
    public function getBanner()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBanner', array());

        return parent::getBanner();
    }

    /**
     * {@inheritDoc}
     */
    public function setBank($bank)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setBank', array($bank));

        return parent::setBank($bank);
    }

    /**
     * {@inheritDoc}
     */
    public function getBank()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getBank', array());

        return parent::getBank();
    }

    /**
     * {@inheritDoc}
     */
    public function setStkBank($stk_bank)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStkBank', array($stk_bank));

        return parent::setStkBank($stk_bank);
    }

    /**
     * {@inheritDoc}
     */
    public function getStkBank()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStkBank', array());

        return parent::getStkBank();
    }

    /**
     * {@inheritDoc}
     */
    public function setCtkBank($ctk_bank)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCtkBank', array($ctk_bank));

        return parent::setCtkBank($ctk_bank);
    }

    /**
     * {@inheritDoc}
     */
    public function getCtkBank()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCtkBank', array());

        return parent::getCtkBank();
    }

    /**
     * {@inheritDoc}
     */
    public function setTimeCreated($time_created)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTimeCreated', array($time_created));

        return parent::setTimeCreated($time_created);
    }

    /**
     * {@inheritDoc}
     */
    public function getTimeCreated()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTimeCreated', array());

        return parent::getTimeCreated();
    }

    /**
     * {@inheritDoc}
     */
    public function setCustomer($customer)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCustomer', array($customer));

        return parent::setCustomer($customer);
    }

    /**
     * {@inheritDoc}
     */
    public function getCustomer()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCustomer', array());

        return parent::getCustomer();
    }

    /**
     * {@inheritDoc}
     */
    public function setCommentShop($comment_shop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCommentShop', array($comment_shop));

        return parent::setCommentShop($comment_shop);
    }

    /**
     * {@inheritDoc}
     */
    public function getCommentShop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCommentShop', array());

        return parent::getCommentShop();
    }

    /**
     * {@inheritDoc}
     */
    public function setReportShop($report_shop)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReportShop', array($report_shop));

        return parent::setReportShop($report_shop);
    }

    /**
     * {@inheritDoc}
     */
    public function getReportShop()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportShop', array());

        return parent::getReportShop();
    }

    /**
     * {@inheritDoc}
     */
    public function setReportRent($report_rent)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReportRent', array($report_rent));

        return parent::setReportRent($report_rent);
    }

    /**
     * {@inheritDoc}
     */
    public function getReportRent()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReportRent', array());

        return parent::getReportRent();
    }

}
