<?php echo $this->headTitle("Danh Sách Luật") ?>
<div class="box bg-white mt-3">
    <div class="box-heading">
        <p class="lead">Luật</p>
        <p class="btn-add">
            <a href="<?php echo $this->Path()->RoleAdd(); ?>" class="btn btn-info">Thêm <i class="icon-plus3"></i></a>
        </p>
    </div>
    <div class="box-body">
        <?php 
            echo $this->Layout()->FlashMessenger();
        ?>
        <table class="table table-responsive table-bordered">
            <thead>
                <tr>
                    <th>Tên</th>
                    <th>Slug</th>
                    <th width="100">Sửa</th>
                    <th width="100">Xóa</th>
                </tr>
            </thead>
            <tbody>
                <?php 
                    $roles = $this->roles;
                    foreach($roles as $role):
                ?>
                    <tr>
                        <td><?php echo $role->getName(); ?></td>
                        <td><?php echo $role->getSlug(); ?></td>
                        <td><a href="<?php echo $this->Path()->RoleEdit($role->getId()); ?>" class="btn btn-outline-warning">Sửa</a></td>
                        <td><?php echo $this->Layout()->Button()->Delete($this->Path()->RoleDelete($role->getId()),'ajax') ?></td>
                    </tr>
                <?php endforeach ?>
            </tbody>
        </table>    
    </div>
</div>