<?php echo $this->headTitle("Đăng Nhập Vào Hệ Thống") ?>
<?php echo $this->doctype(); ?>
<html lang="en">

<head>
    <meta charset="utf-8">
    <?php echo $this->headTitle('ZF2 '. $this->translate('Skeleton Application'))->setSeparator(' - ')->setAutoEscape(false) ?>

    <?php echo $this->headMeta()
        ->appendName('viewport', 'width=device-width, initial-scale=1.0')
        ->appendHttpEquiv('X-UA-Compatible', 'IE=edge')
    ?>

    <!-- Le styles -->
    <?php echo $this->headLink(array('rel' => 'shortcut icon', 'type' => 'image/vnd.microsoft.icon', 'href' => $this->basePath() . '/img/favicon.ico'))
                    ->prependStylesheet($this->basePath() . '/css/style.css')
                    ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.css')
                    ->prependStylesheet($this->basePath() . '/plugin/perfect-scrollbar/css/perfect-scrollbar.min.css')
                    ->prependStylesheet($this->basePath() . '/plugin/icon/icomoon/styles.css')
                    ->prependStylesheet($this->basePath() . '/plugin/font-awesome/css/font-awesome.min.css')
                    ->prependStylesheet($this->basePath() . '/plugin/alertify.css')
                    ->prependStylesheet('https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/css/bootstrap.min.css') 
                    ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.2.0/dropzone.css') 
                    ->prependStylesheet('https://fonts.googleapis.com/css?family=Open+Sans:400,600,700,800') 
                    ->prependStylesheet('https://code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css') 
                    ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/css/select2.min.css') 
                    ->prependStylesheet('https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.25/jquery.fancybox.min.css') 
    ?>
</head>

<body class="login">
    <?php echo $this->content; ?>
    <!-- Scripts -->
    <?php echo $this->headScript()
        ->prependFile($this->basePath() . '/js/script.js')
        ->prependFile($this->basePath() . '/plugin/sortable/Sortable.min.js')
        ->prependFile($this->basePath() . '/plugin/perfect-scrollbar/js/perfect-scrollbar.jquery.min.js')
        ->prependFile($this->basePath() . '/plugin/nestable/jquery.nestable.js')
        ->prependFile($this->basePath() . '/plugin/alertify.js')
        ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/raphael/2.1.0/raphael-min.js')
        ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/morris.js/0.5.1/morris.min.js')
        ->prependFile($this->basePath() . '/js/respond.min.js', 'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile($this->basePath() . '/js/html5shiv.js',   'text/javascript', array('conditional' => 'lt IE 9',))
        ->prependFile("https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta/js/bootstrap.min.js")
        ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js')
        ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.4/js/select2.min.js')
        ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/dropzone/5.2.0/dropzone.js')
        ->prependFile('http://cdnjs.cloudflare.com/ajax/libs/waypoints/2.0.3/waypoints.min.js')
        ->prependFile($this->basePath() . '/plugin/jquery.counterup.min.js')
        ->prependFile('https://cdnjs.cloudflare.com/ajax/libs/fancybox/3.1.25/jquery.fancybox.min.js')
        ->prependFile($this->basePath() . '/plugin/jquery-ui.js')
        ->prependFile($this->basePath() . '/plugin/jquery.min.js')
    ; ?>
    <?php echo $this->inlineScript() ?>
</body>

</html>