<?php echo $this->headTitle($this->Data()->Site()['sitedescription']) ?>
<?php 
$url_ajax = $this->url('ajax',array('action' => 'load-rent'));
$url_ajax_rent = $this->url('ajax',array('action' => 'load-shop'));
$url_ajax_login = $this->url('login');
$url_ajax_history_rent = $this->url('history_rent');
$url_ajax_card = $this->url('card');
 $this->inlineScript()->captureStart();
 
echo <<<JS
    function htmlSuccess(title = 'THUÊ TÀI KHOẢN',value = 'THUÊ THÀNH CÔNG',is_button = 1)
    {
      var xhtml ='';
      xhtml += '<div id="popupR">';
      xhtml += '<h4 class="text-center" >'+title+'</h4>';
      xhtml += '<div class="hr"></div>';
      xhtml += '<h3 class="text-center"><strong>'+value+'</strong></h3>';
      if(is_button == 1)
      {
        xhtml += '<div class="text-center w-100">';
          xhtml += '<a href="$url_ajax_history_rent" class="ui button large black mb-15">VÀO LỊCH SỬ GIAO DỊCH</a>';
        xhtml += '</div>';
      }else if(is_button == 'login'){
        xhtml += '<div class="text-center w-100">';
          xhtml += '<a href="$url_ajax_login" class="ui button large black mb-15">ĐĂNG NHẬP</a>';
        xhtml += '</div>';
      }else if(is_button == false)
      {
        xhtml += '<div class="text-center w-100">';
          xhtml += '<button id="close" class="ui button fluid black mb-15">ĐÓNG</button>';
        xhtml += '</div>';
      }
      xhtml += '</div>';
      return xhtml;
    }

    function htmlError(data = 'THUÊ TÀI KHOẢN')
    {
      var xhtml ='';
      xhtml += '<div id="popupR">';
      xhtml += '<h4 class="text-center" >'+data+'</h4>';
      xhtml += '<div class="hr"></div>';
      xhtml += '<h3 class="text-center"><strong>KHÔNG ĐỦ TIỀN</strong></h3>';
      xhtml += '<div class="text-center w-100">';
        xhtml += '<a href="$url_ajax_card" class="ui button large black mb-15">NẠP TIỀN</a>';
      xhtml += '</div>';
      xhtml += '</div>';
      return xhtml;
    }
    $(".filter-left .btn-filter-rent").click(function(){
      page = 1;
      $(".filter-left .btn-filter-rent").removeClass("active");
      $(this).addClass("active");
      var game = strip_tags($(this).data('game'));
      current_game = game;
      $.ajax({
        type: 'POST',
        url: '$url_ajax',
        beforeSend: function() {
            $(".loader-rent").addClass("active");
        },
        data: { game: game,ready : is_ready,page:page,customer_id: customer_id},
        success: function(data)
        {
          var result = data.result;
          $("#count_sansang").text(data.count.rent_sansang);
          $("#count_dathue").text(data.count.rent_dathue);
          $(".div-rent > div:not(.loader-rent)").remove();
          if(is_ready == 1)
          {
            $.each(result, function(i, value) {
              $(".div-rent").append(htmlAjaxRent(value));
            });
          }else{
            $.each(result, function(i, value) {
              $(".div-rent").append(htmlAjaxRent2(value));
            });
          }
        },
        complete: function() {
            $(".loader-rent").removeClass("active");
          $('.special.cards .image').dimmer({
          on: 'hover'
          });
          $('.ui.dropdown').dropdown();
          if(is_ready == 2)
          {
            rent_time_format();
          }
        },
        dataType: 'json'
      });
    });

    $(".filter-right .btn-filter").click(function(){
      page = 1;
      $(".filter-right .btn-filter").removeClass("active");
      $(this).addClass("active");
      var ready = $(this).data('ready');
      is_ready = ready;
      $.ajax({
        type: 'POST',
        url: '$url_ajax',
        beforeSend: function() {
            $(".loader-rent").addClass("active");
        },
        data: { game: current_game,ready : ready,page:page,customer_id : customer_id},
        success: function(data)
        {
          var result = data.result;
          $("#count_sansang").text(data.count.rent_sansang);
          $("#count_dathue").text(data.count.rent_dathue);
          $(".div-rent > div:not(.loader-rent)").remove();
          if(is_ready == 1)
          {
            $.each(result, function(i, value) {
              $(".div-rent").append(htmlAjaxRent(value));
            });
          }else{
            $.each(result, function(i, value) {
              $(".div-rent").append(htmlAjaxRent2(value))
            });
          }
        },
        complete: function() {
          $(".loader-rent").removeClass("active");
          $('.special.cards .image').dimmer({
          on: 'hover'
          });
          $('.ui.dropdown').dropdown();
          if(is_ready == 2)
          {
            rent_time_format();
          }
        },
        dataType: 'json'
      });
    });
    $(".btn-more").click(function(){
        page = page + 1;
        $.ajax({
          type: 'POST',
          url: "$url_ajax",
          beforeSend: function() {
              $(".loader-rent").addClass("active");
          },
          data: { game: current_game,ready : is_ready,page:page,customer_id: customer_id},
          success: function(data)
          {
            var flag = false;
            var result = data.result;
            if(result.length == 0)
            {
              flag = true;
            }
            
            if(is_ready == 1)
            {
              $.each(result, function(i, value) {
              if($(".btn-rent[data-id="+value.id+"]").length == 1)
              {
                flag = true;
              }else{
                $(".div-rent").append(htmlAjaxRent(value));
              }
            });
            }else{
              $.each(result, function(i, value) {
              if($(".btn-rent[data-id="+value.id+"]").length == 1)
              {
                flag = true;
              }else{
                $(".div-rent").append(htmlAjaxRent2(value));
              }
            });
            }
            if(flag == true)
            {
              swal("Thông báo !", "Đã load hết tài khoản !", "warning");
            }
          },
          complete: function() {
            $(".loader-rent").removeClass("active");
            $('.special.cards .image').dimmer({
            on: 'hover'
            });
            $('.ui.dropdown').dropdown();
            if(is_ready == 2)
            {
              rent_time_format();
            }
          },
          dataType: 'json'
        });
    });

    $(".div-rent").on('click','.btn-rent',function(){
      var id = $(this).data('id');
      var value = $(this).parents('.extra.content').prev('.content').find('select').val();
      var price = $(this).parents('.extra.content').prev('.content').find('.money_'+value).val();
      var img = $(this).parents('.extra.content').prevAll('.image').find('img').attr('src');
      $.post("$url_ajax_rent", { id: id})
      .done(function(data) {
        var result = data.result;
        var data = {id: id,game: result.game,time: value,price: price,shop: result.shop,url_shop: result.url_shop,img: img};
        $("#popupInfo").html(htmlRent(data));
        move_center('#popupCenter');
      });

      $("#popupBg").show();
    });
JS;
$this->inlineScript()->captureEnd(); ?>

    <section class="ui container banner">
      <div class="ui icon message">
        <i class="hand rock icon"></i>
        <div class="content">
          <div class="header">
            Những điều bạn cần biết trước khi thuê
          </div>
          <p>Sử dụng tài khoản clone sẽ không được chấp nhận !</p>
          <p>Nói không với sử dụng hack</p>
        </div>
      </div>
    </section>
    <article class="ui container wrapper">
      <section class="filter filter-rent-list" data-id="0" style="display: block;">
        <div class="filter-left">
          <button class="btn-filter btn-filter-rent active" data-game="home"><i class="home icon m-0"></i></button>
          <?php foreach($this->FrontendData()->Category() as $key => $category): ?>
            <button class="btn-filter btn-filter-rent" data-game="<?php echo $key; ?>"><?php echo $category; ?></button>
          <?php endforeach; ?>
        </div>
        <div class="filter-right">
          <button class="btn-filter active" data-ready="1"><span id="count_sansang"><?php echo $this->count['rent_sansang']; ?></span> Sẵn sàng</button>
          <button class="btn-filter" data-ready="2"><span id="count_dathue"><?php echo $this->count['rent_dathue']; ?></span> Đang được thuê</button>
        </div>
      </section>
      <div class="ui four column doubling stackable grid segment div-rent" style="clear: both;border: none;box-shadow: none;">
          <div class="ui inverted dimmer loader-rent">
            <div class="ui loader"></div>
          </div>
          <?php foreach($this->rents as $rent): ?>
          <div class="column">
            <div class="ui special cards">
              <div class="card">
                <div class="blurring dimmable image">
                  <div class="ui dimmer">
                    <div class="content">
                      <div class="center">
                        <p><a href="<?php echo $this->url('shop_info',array('id' => $rent->getCustomer()->getShop()->getId())); ?>"><?php echo $rent->getCustomer()->getShop()->getShopName(); ?></a></p>
                        <a href="<?php echo $rent->getCustomer()->getShop()->getUrlFacebook(); ?>" target="_blank"><i class="icon facebook"></i></a>
                      </div>
                    </div>
                  </div>
                  <img src="<?php echo $rent->getCategory()->getImage(); ?>" class="img-game">
                </div>
                <div class="content">
                  <select class="ui dropdown fluid">
                    <?php $rent_time = unserialize($rent->getRentTime()); ?>
                    <option value="3" <?php echo (array_key_exists(3,$rent_time)) ? '' : 'disabled' ?>><?php echo (array_key_exists(3,$rent_time)) ? number_format($rent_time[3]).'đ/3h' : '0đ/3h' ?></option>
                    <option value="8" <?php echo (array_key_exists(8,$rent_time)) ? '' : 'disabled' ?>><?php echo (array_key_exists(8,$rent_time)) ? number_format($rent_time[8]).'đ/8h' : '0đ/8h' ?></option>
                    <option value="20" <?php echo (array_key_exists(20,$rent_time)) ? '' : 'disabled' ?>><?php echo (array_key_exists(20,$rent_time)) ? number_format($rent_time[20]).'đ/20h' : '0đ/20h' ?></option>
                    <option value="36" <?php echo (array_key_exists(36,$rent_time)) ? '' : 'disabled' ?>><?php echo (array_key_exists(36,$rent_time)) ? number_format($rent_time[36]).'đ/36h' : '0đ/36h' ?></option>
                    <option value="72" <?php echo (array_key_exists(72,$rent_time)) ? '' : 'disabled' ?>><?php echo (array_key_exists(72,$rent_time)) ? number_format($rent_time[72]).'đ/72h' : '0đ/72h' ?></option>
                    
                  </select>
                  <input style="display: none;" class="money_3" value="<?php echo (array_key_exists(3,$rent_time)) ? $rent_time[3] : 0 ?>">
                    <input style="display: none;" class="money_8" value="<?php echo (array_key_exists(8,$rent_time)) ? $rent_time[8] : 0 ?>">
                    <input style="display: none;" class="money_20" value="<?php echo (array_key_exists(20,$rent_time)) ? $rent_time[20] : 0 ?>">
                    <input style="display: none;" class="money_36" value="<?php echo (array_key_exists(36,$rent_time)) ? $rent_time[36] : 0 ?>">
                    <input style="display: none;" class="money_72" value="<?php echo (array_key_exists(72,$rent_time)) ? $rent_time[72] : 0 ?>">
                </div>
                <div class="extra content">
                  <div class="ui buttons fluid">
                    <button class="ui button black btn-rent" data-id="<?php echo $rent->getId(); ?>">Thuê Ngay</button>
                    <div class="or" data-text="&"></div>
                    <button class="ui button" data-tooltip="<?php echo $rent->getDescription(); ?>"><i class="info icon"></i></button>
                  </div>
                </div>
              </div>
            </div>
          </div>
        <?php endforeach; ?>
      </div>
      </div>
      <section class="more">
        <button class="ui button black fluid btn-more">XEM THÊM</button>
      </section>
    </article>
    