<?php echo $this->headTitle("Danh Sách Game") ?>
<div class="box bg-white mt-3">
    <div class="box-heading">
        <p class="lead">Category</p>
        <p class="btn-add">
            <a href="<?php echo $this->Path()->CategoryAdd(); ?>" class="btn btn-info">Thêm <i class="icon-plus3"></i></a>
        </p>
    </div>
    <div class="box-body">
        <?php 
            echo $this->Layout()->FlashMessenger();
        ?>
        <table class="table table-responsive table-bordered" data-toggle="table" data-pagination="true" data-search="true">
            <thead>
                <tr>
                    <th>Code</th>
                    <th>Name</th>
                    <th width="100">Sửa</th>
                    <th width="100">Xóa</th>
                </tr>
            </thead>
            <tbody>
            <?php 
            foreach($this->categories as $category):
            ?>
                <tr>
                    <td><?php echo $category->getCode(); ?></td>
                    <td><?php echo $category->getName(); ?></td>
                    <td><?php echo $this->Layout()->Button()->Edit($this->Path()->CategoryEdit($category->getId())); ?></td>
                    <td><?php echo $this->Layout()->Button()->Delete($this->Path()->CategoryDelete($category->getId()),'ajax'); ?></td>
                </tr>
            <?php endforeach ?>
            </tbody>
        </table> 
    </div>
</div>