<?php echo $this->headTitle("Thêm Menu") ?>
<div class="row">
    <div class="col-12 col-sm-2">
        <div class="mt-3">
            <div id="accordion" role="tablist">
              <div class="card card-menu">
                <a class="collapsed toggleCollapsed" data-toggle="collapse" href="#custom" aria-expanded="false" aria-controls="custom">
                    <div class="card-header card-header-menu" role="tab" id="headingOne">
                        <i class="icon-cube3"></i>Add Link
                    </div>
                </a>
                <div id="custom" class="collapse" role="tabpanel" aria-labelledby="headingOne" data-parent="#accordion">
                  <div class="card-body">
                    <div class="form-group">
                        <label><small class="font-weight-500">Tiêu đề</small></label>
                        <input type="text" class="form-control" id="title">
                    </div>
                    <div class="form-group">
                        <label><small class="font-weight-500">Url</small></label>
                        <input type="text" class="form-control" id="url" placeholder="http://">
                    </div>
                    <div class="form-group">
                        <label><small class="font-weight-500">Font icon class</small></label>
                        <input type="text" class="form-control" id="icon" placeholder="fa fa-something">
                    </div>
                    <div class="text-right">
                        <button type="button" class="btn btn-add-menu btn-info btn-sm mt-2 btn-mini">Thêm <i class="fa fa-plus"></i></button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card card-menu">
                <a class="collapsed toggleCollapsed" data-toggle="collapse" href="#categories" aria-expanded="false" aria-controls="categories">
                    <div class="card-header card-header-menu" role="tab" id="headingTwo">
                        <i class="icon-cube3"></i>Categories
                    </div>
                </a>
                <div id="categories" class="collapse" role="tabpanel" aria-labelledby="headingTwo" data-parent="#accordion">
                  <div class="card-body">
                    <ul class="p-0">
                        <?php foreach($this->categories as $k => $category): ?>
                        <li><input class="cbx-input cbx-child" id="<?php echo $k; ?>" value="<?php echo $k; ?>" type="checkbox" /><label class="cbx" for="<?php echo $k; ?>"></label><label class="lbl" id="title" for="<?php echo $k; ?>"><?php echo $category; ?></label></li>
                        <?php endforeach ?>
                    </ul>
                    <div class="text-right">
                        <button type="button" class="btn btn-info btn-add-menu btn-sm btn-mini">Thêm <i class="fa fa-plus"></i></button>
                    </div>
                  </div>
                </div>
              </div>
              <div class="card card-menu">
                <a class="collapsed toggleCollapsed" data-toggle="collapse" href="#page" aria-expanded="false" aria-controls="page">
                    <div class="card-header card-header-menu" role="tab" id="headingThree">
                        <i class="icon-cube3"></i>Page
                    </div>
                </a>
                <div id="page" class="collapse" role="tabpanel" aria-labelledby="headingThree" data-parent="#accordion">
                  <div class="card-body">
                    <ul class="p-0">
                        <li><input class="cbx-input cbx-child" id="<?php echo $k; ?>" value="<?php echo $k; ?>" type="checkbox" /><label class="cbx" for="<?php echo $k; ?>"></label><label class="lbl" id="title" for="<?php echo $k; ?>"><?php echo $category; ?></label></li>
                    </ul>
                    <div class="text-right">
                        <button type="button" class="btn btn-info btn-add-menu btn-sm btn-mini">Thêm <i class="fa fa-plus"></i></button>
                    </div>
                  </div>
                </div>
              </div>
            </div>
        </div>
    </div>
    <div class="col-12 col-sm-10">
        <?php
            $form = $this->form;
            $form->prepare();
            $form->setAttribute('action',$this->Path()->MenuAdd());
            echo $this->form()->openTag($form);
            echo $this->formElement($form->get('csrf'));
            echo $this->formElement($form->get('data'));
        ?>
        <div class="box bg-white mt-3">
            <div class="box-heading">
                <p class="lead">Thông tin Menu</p>
                <div class="btn-add">
                    <button class="btn btn-info">Lưu <i class="fa fa-floppy-o" aria-hidden="true"></i></button>
                </div>
            </div>
            <div class="box-body box-body-form">
                <div class="box-form">
                    <div class="box-form-heading">
                        <small class="box-form-title">Thông tin quyền</small>
                        <p class="box-close">
                            <i class="fa fa-angle-down" aria-hidden="true"></i>
                        </p>
                    </div>
                    <div class="box-form-content">
                        <div class="row">
                            <div class="col-4">
                                <?php echo $this->formLabel($form->get('name')); ?>
                            </div>
                            <div class="col-8">
                                <?php echo $this->formElement($form->get('name')); ?>
                                <?php echo $this->formElementErrors($form->get('name')); ?>
                            </div>
                            <div class="col-4">
                                <?php echo $this->formLabel($form->get('code')); ?>
                            </div>
                            <div class="col-8">
                                <?php echo $this->formElement($form->get('code')); ?>
                                <?php echo $this->formElementErrors($form->get('code')); ?>
                            </div>
                        </div>
                    </div>
                </div>
                <div class="box-form mt-3">
                    <div class="box-form-heading">
                        <small class="box-form-title">Cấu hình</small>
                        <p class="box-close">
                            <i class="fa fa-angle-down" aria-hidden="true"></i>
                        </p>
                    </div>
                    <div class="box-form-content">
                        <div class="row">
                            <div class="col-4">
                                <?php echo $this->formLabel($form->get('status')); ?>
                            </div>
                            <div class="col-8">
                                <?php echo $this->formElement($form->get('status')); ?>
                                <?php echo $this->formElementErrors($form->get('status')); ?>
                            </div>
                            <div class="col-4">
                                <p class="box-left-title">Cấu trúc</p>
                            </div>
                            <div class="col-8">
                                <div class="dd" id="nestable">
                                    <ol class="dd-list">
                                    </ol>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>  
            </div>
        </div>
        <?php 
            $this->form()->closeTag();
        ?>
    </div>
</div>