<?php echo $this->headTitle("Danh Sách Menu") ?>
<div class="box bg-white mt-3">
    <div class="box-heading">
        <p class="lead">Category</p>
        <p class="btn-add">
            <a href="<?php echo $this->Path()->MenuAdd(); ?>" class="btn btn-info">Thêm <i class="icon-plus3"></i></a>
        </p>
    </div>
    <div class="box-body">
        <?php 
            echo $this->Layout()->FlashMessenger();
        ?>
        <table class="table table-responsive table-bordered">
            <thead>
                <tr>
                    <th>Tên</th>
                    <th width="150">Tạo lúc</th>
                    <th width="150">Trạng thái</th>
                    <th >Action</th>
                </tr>
            </thead>
            <tbody>
                <?php foreach($this->menus as $menu): ?>
                <tr>
                    <td><?php echo $menu->getName(); ?></td>
                    <td><?php echo $menu->getTimeCreated(); ?></td>
                    <?php echo $this->Layout()->Status($menu->getStatus(),1); ?>
                    <td><?php echo $this->Layout()->Button()->Edit($this->Path()->MenuEdit($menu->getId())); ?>
                        <?php echo $this->Layout()->Button()->Delete($this->Path()->MenuDelete($menu->getId()),'ajax'); ?>
                    </td>
                </tr>
                <?php endforeach; ?>
            </tbody>
        </table> 
    </div>
</div>