<ol class="breadcrumb m-0 p-0">
    <li class="breadcrumb-item"><a href="<?php echo $this->url('zflex'); ?>">ZFlex</a></li>
    <?php foreach($this->pages as $page): ?>
        <?php /* @var $page \Zend\Navigation\Page\Mvc */ ?>
        <?php if( ! $page->isActive()): ?>
            <li>
                <a href="<?php echo $page->getHref() ?>"><?php echo $page->getLabel() ?></a> 
                <span class="divider">/</span>
            </li>
        <?php else: ?>
            <li class="breadcrumb-item active">
                <a href="<?php echo $page->getHref() ?>"><?php echo $page->getLabel() ?></a> 
            </li>
        <?php endif ?>
    <?php endforeach ?>
</ol>